import {
    Box,
    Button,
    Center,
    Divider,
    Heading,
    Text,
    VStack,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import router from "next/router";

const Home: NextPage = () => {
    return (
        <Box h='100vh' w='100vw' backgroundColor='brand.background'>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Center h='100%' w='100%'>
                <VStack maxW='800px' mx='auto'>
                    <Heading color='white'>Hello World!</Heading>
                    <Divider />
                    <Box w='40%' justifyContent='center' pt={3}>
                        <Button
                            variant='solid'
                            w='100%'
                            bg='pink.400'
                            color='white'
                            onClick={() => router.push("/register")}
                        >
                            Register
                        </Button>
                        <Center p={2}>
                            <Text color='white'>or</Text>
                        </Center>
                        <Button
                            w='100%'
                            variant='outline'
                            color='pink.400'
                            borderColor='pink.400'
                            onClick={() => router.push("/login")}
                        >
                            Log In
                        </Button>
                    </Box>
                </VStack>
            </Center>
        </Box>
    );
};

export default Home;
